// Code generated by counterfeiter. DO NOT EDIT.
package handlerfakes

import (
	"context"
	"sync"

	"github.com/smartatransit/fivepoints/api/v1/schedule"
	"github.com/smartatransit/fivepoints/cmd/scheduleapi/handler"
)

type FakeGetScheduleEndpoint struct {
	Stub        func(context.Context, *schedule.GetScheduleRequest) (*schedule.GetScheduleResponse, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 context.Context
		arg2 *schedule.GetScheduleRequest
	}
	returns struct {
		result1 *schedule.GetScheduleResponse
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 *schedule.GetScheduleResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetScheduleEndpoint) Spy(arg1 context.Context, arg2 *schedule.GetScheduleRequest) (*schedule.GetScheduleResponse, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 context.Context
		arg2 *schedule.GetScheduleRequest
	}{arg1, arg2})
	fake.recordInvocation("GetScheduleEndpoint", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.returns.result1, fake.returns.result2
}

func (fake *FakeGetScheduleEndpoint) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeGetScheduleEndpoint) Calls(stub func(context.Context, *schedule.GetScheduleRequest) (*schedule.GetScheduleResponse, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeGetScheduleEndpoint) ArgsForCall(i int) (context.Context, *schedule.GetScheduleRequest) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2
}

func (fake *FakeGetScheduleEndpoint) Returns(result1 *schedule.GetScheduleResponse, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 *schedule.GetScheduleResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGetScheduleEndpoint) ReturnsOnCall(i int, result1 *schedule.GetScheduleResponse, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 *schedule.GetScheduleResponse
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 *schedule.GetScheduleResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeGetScheduleEndpoint) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetScheduleEndpoint) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.GetScheduleEndpoint = new(FakeGetScheduleEndpoint).Spy
