// Code generated by counterfeiter. DO NOT EDIT.
package handlerfakes

import (
	"context"
	"sync"

	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/smartatransit/fivepoints/cmd/scheduleapi/handler"
)

type FakeDynamoQuerier struct {
	QueryWithContextStub        func(context.Context, *dynamodb.QueryInput, ...request.Option) (*dynamodb.QueryOutput, error)
	queryWithContextMutex       sync.RWMutex
	queryWithContextArgsForCall []struct {
		arg1 context.Context
		arg2 *dynamodb.QueryInput
		arg3 []request.Option
	}
	queryWithContextReturns struct {
		result1 *dynamodb.QueryOutput
		result2 error
	}
	queryWithContextReturnsOnCall map[int]struct {
		result1 *dynamodb.QueryOutput
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDynamoQuerier) QueryWithContext(arg1 context.Context, arg2 *dynamodb.QueryInput, arg3 ...request.Option) (*dynamodb.QueryOutput, error) {
	fake.queryWithContextMutex.Lock()
	ret, specificReturn := fake.queryWithContextReturnsOnCall[len(fake.queryWithContextArgsForCall)]
	fake.queryWithContextArgsForCall = append(fake.queryWithContextArgsForCall, struct {
		arg1 context.Context
		arg2 *dynamodb.QueryInput
		arg3 []request.Option
	}{arg1, arg2, arg3})
	fake.recordInvocation("QueryWithContext", []interface{}{arg1, arg2, arg3})
	fake.queryWithContextMutex.Unlock()
	if fake.QueryWithContextStub != nil {
		return fake.QueryWithContextStub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.queryWithContextReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDynamoQuerier) QueryWithContextCallCount() int {
	fake.queryWithContextMutex.RLock()
	defer fake.queryWithContextMutex.RUnlock()
	return len(fake.queryWithContextArgsForCall)
}

func (fake *FakeDynamoQuerier) QueryWithContextCalls(stub func(context.Context, *dynamodb.QueryInput, ...request.Option) (*dynamodb.QueryOutput, error)) {
	fake.queryWithContextMutex.Lock()
	defer fake.queryWithContextMutex.Unlock()
	fake.QueryWithContextStub = stub
}

func (fake *FakeDynamoQuerier) QueryWithContextArgsForCall(i int) (context.Context, *dynamodb.QueryInput, []request.Option) {
	fake.queryWithContextMutex.RLock()
	defer fake.queryWithContextMutex.RUnlock()
	argsForCall := fake.queryWithContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeDynamoQuerier) QueryWithContextReturns(result1 *dynamodb.QueryOutput, result2 error) {
	fake.queryWithContextMutex.Lock()
	defer fake.queryWithContextMutex.Unlock()
	fake.QueryWithContextStub = nil
	fake.queryWithContextReturns = struct {
		result1 *dynamodb.QueryOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamoQuerier) QueryWithContextReturnsOnCall(i int, result1 *dynamodb.QueryOutput, result2 error) {
	fake.queryWithContextMutex.Lock()
	defer fake.queryWithContextMutex.Unlock()
	fake.QueryWithContextStub = nil
	if fake.queryWithContextReturnsOnCall == nil {
		fake.queryWithContextReturnsOnCall = make(map[int]struct {
			result1 *dynamodb.QueryOutput
			result2 error
		})
	}
	fake.queryWithContextReturnsOnCall[i] = struct {
		result1 *dynamodb.QueryOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeDynamoQuerier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.queryWithContextMutex.RLock()
	defer fake.queryWithContextMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDynamoQuerier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.DynamoQuerier = new(FakeDynamoQuerier)
