// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schedule.proto

package schedule

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetScheduleRequest struct {
	StartDate            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	Station              string               `protobuf:"bytes,3,opt,name=Station,proto3" json:"Station,omitempty"`
	Destination          string               `protobuf:"bytes,4,opt,name=Destination,proto3" json:"Destination,omitempty"`
	LastEvaluatedKey     string               `protobuf:"bytes,5,opt,name=LastEvaluatedKey,proto3" json:"LastEvaluatedKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetScheduleRequest) Reset()         { *m = GetScheduleRequest{} }
func (m *GetScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*GetScheduleRequest) ProtoMessage()    {}
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00842e68e05382a, []int{0}
}

func (m *GetScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScheduleRequest.Unmarshal(m, b)
}
func (m *GetScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScheduleRequest.Marshal(b, m, deterministic)
}
func (m *GetScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScheduleRequest.Merge(m, src)
}
func (m *GetScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_GetScheduleRequest.Size(m)
}
func (m *GetScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetScheduleRequest proto.InternalMessageInfo

func (m *GetScheduleRequest) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *GetScheduleRequest) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *GetScheduleRequest) GetStation() string {
	if m != nil {
		return m.Station
	}
	return ""
}

func (m *GetScheduleRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *GetScheduleRequest) GetLastEvaluatedKey() string {
	if m != nil {
		return m.LastEvaluatedKey
	}
	return ""
}

type Schedule struct {
	PrimaryKey           string   `protobuf:"bytes,1,opt,name=PrimaryKey,proto3" json:"PrimaryKey,omitempty"`
	SortKey              string   `protobuf:"bytes,2,opt,name=SortKey,proto3" json:"SortKey,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=Destination,proto3" json:"Destination,omitempty"`
	Direction            string   `protobuf:"bytes,4,opt,name=Direction,proto3" json:"Direction,omitempty"`
	EventTime            string   `protobuf:"bytes,5,opt,name=EventTime,proto3" json:"EventTime,omitempty"`
	Line                 string   `protobuf:"bytes,6,opt,name=Line,proto3" json:"Line,omitempty"`
	NextArrival          string   `protobuf:"bytes,7,opt,name=NextArrival,proto3" json:"NextArrival,omitempty"`
	Station              string   `protobuf:"bytes,8,opt,name=Station,proto3" json:"Station,omitempty"`
	TrainID              string   `protobuf:"bytes,9,opt,name=TrainID,proto3" json:"TrainID,omitempty"`
	WaitingSeconds       string   `protobuf:"bytes,10,opt,name=WaitingSeconds,proto3" json:"WaitingSeconds,omitempty"`
	WaitingTime          string   `protobuf:"bytes,11,opt,name=WaitingTime,proto3" json:"WaitingTime,omitempty"`
	TTL                  int64    `protobuf:"varint,12,opt,name=TTL,proto3" json:"TTL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00842e68e05382a, []int{1}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *Schedule) GetSortKey() string {
	if m != nil {
		return m.SortKey
	}
	return ""
}

func (m *Schedule) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Schedule) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *Schedule) GetEventTime() string {
	if m != nil {
		return m.EventTime
	}
	return ""
}

func (m *Schedule) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *Schedule) GetNextArrival() string {
	if m != nil {
		return m.NextArrival
	}
	return ""
}

func (m *Schedule) GetStation() string {
	if m != nil {
		return m.Station
	}
	return ""
}

func (m *Schedule) GetTrainID() string {
	if m != nil {
		return m.TrainID
	}
	return ""
}

func (m *Schedule) GetWaitingSeconds() string {
	if m != nil {
		return m.WaitingSeconds
	}
	return ""
}

func (m *Schedule) GetWaitingTime() string {
	if m != nil {
		return m.WaitingTime
	}
	return ""
}

func (m *Schedule) GetTTL() int64 {
	if m != nil {
		return m.TTL
	}
	return 0
}

type GetScheduleResponse struct {
	Schedules            []*Schedule `protobuf:"bytes,1,rep,name=Schedules,proto3" json:"Schedules,omitempty"`
	LastEvaluatedKey     string      `protobuf:"bytes,2,opt,name=LastEvaluatedKey,proto3" json:"LastEvaluatedKey,omitempty"`
	ResultLength         int32       `protobuf:"varint,3,opt,name=ResultLength,proto3" json:"ResultLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetScheduleResponse) Reset()         { *m = GetScheduleResponse{} }
func (m *GetScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*GetScheduleResponse) ProtoMessage()    {}
func (*GetScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00842e68e05382a, []int{2}
}

func (m *GetScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScheduleResponse.Unmarshal(m, b)
}
func (m *GetScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScheduleResponse.Marshal(b, m, deterministic)
}
func (m *GetScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScheduleResponse.Merge(m, src)
}
func (m *GetScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_GetScheduleResponse.Size(m)
}
func (m *GetScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetScheduleResponse proto.InternalMessageInfo

func (m *GetScheduleResponse) GetSchedules() []*Schedule {
	if m != nil {
		return m.Schedules
	}
	return nil
}

func (m *GetScheduleResponse) GetLastEvaluatedKey() string {
	if m != nil {
		return m.LastEvaluatedKey
	}
	return ""
}

func (m *GetScheduleResponse) GetResultLength() int32 {
	if m != nil {
		return m.ResultLength
	}
	return 0
}

func init() {
	proto.RegisterType((*GetScheduleRequest)(nil), "schedule.GetScheduleRequest")
	proto.RegisterType((*Schedule)(nil), "schedule.Schedule")
	proto.RegisterType((*GetScheduleResponse)(nil), "schedule.GetScheduleResponse")
}

func init() { proto.RegisterFile("schedule.proto", fileDescriptor_d00842e68e05382a) }

var fileDescriptor_d00842e68e05382a = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0xda, 0xdd, 0x6d, 0x3b, 0x5d, 0x2d, 0x95, 0x11, 0x92, 0x55, 0x0a, 0x54, 0x39, 0xa0,
	0x6a, 0x25, 0x1a, 0x28, 0x1c, 0x10, 0x37, 0xa4, 0x56, 0x08, 0x51, 0x21, 0x94, 0x54, 0xe2, 0xec,
	0x6d, 0x87, 0xac, 0xa5, 0xd4, 0x29, 0xf6, 0x24, 0x62, 0x39, 0xf2, 0x0b, 0x1c, 0xf8, 0x30, 0x7e,
	0x81, 0x03, 0x07, 0x3e, 0x02, 0xc5, 0x4e, 0x36, 0xe9, 0x76, 0x11, 0x37, 0xcf, 0x7b, 0x6f, 0xfc,
	0x9e, 0x3d, 0x36, 0x9c, 0x99, 0xf5, 0x25, 0x6e, 0xb2, 0x04, 0xa7, 0x3b, 0x9d, 0x52, 0xca, 0xba,
	0x55, 0x3d, 0x7c, 0x14, 0xa7, 0x69, 0x9c, 0x60, 0x60, 0xf1, 0x8b, 0xec, 0x53, 0x40, 0x72, 0x8b,
	0x86, 0xc4, 0x76, 0xe7, 0xa4, 0xc3, 0x51, 0x29, 0x10, 0x3b, 0x19, 0x08, 0xa5, 0x52, 0x12, 0x24,
	0x53, 0x65, 0x1c, 0xeb, 0xff, 0xf1, 0x80, 0xbd, 0x41, 0x8a, 0xca, 0xed, 0x42, 0xfc, 0x9c, 0xa1,
	0x21, 0xf6, 0x12, 0x7a, 0x11, 0x09, 0x4d, 0x73, 0x41, 0xc8, 0xbd, 0xb1, 0x37, 0xe9, 0xcf, 0x86,
	0x53, 0xb7, 0xd1, 0xb4, 0x72, 0x9a, 0xae, 0x2a, 0xa7, 0xb0, 0x16, 0xb3, 0x17, 0xd0, 0x59, 0xa8,
	0x8d, 0xed, 0x6b, 0xfd, 0xb7, 0xaf, 0x92, 0x32, 0x0e, 0x9d, 0xc8, 0x05, 0xe3, 0xed, 0xb1, 0x37,
	0xe9, 0x85, 0x55, 0xc9, 0xc6, 0xd0, 0x9f, 0xa3, 0x21, 0xa9, 0x1c, 0x7b, 0x64, 0xd9, 0x26, 0xc4,
	0xce, 0x61, 0xb0, 0x14, 0x86, 0x16, 0xb9, 0x48, 0x32, 0x41, 0xb8, 0x79, 0x87, 0x57, 0xfc, 0xd8,
	0xca, 0x0e, 0x70, 0xff, 0x77, 0x0b, 0xba, 0xd5, 0x59, 0xd9, 0x43, 0x80, 0x0f, 0x5a, 0x6e, 0x85,
	0xbe, 0x2a, 0x5a, 0x3c, 0xdb, 0xd2, 0x40, 0x6c, 0xa8, 0x54, 0x53, 0x41, 0xb6, 0xca, 0x50, 0xae,
	0xbc, 0x19, 0xaa, 0x7d, 0x18, 0x6a, 0x04, 0xbd, 0xb9, 0xd4, 0xb8, 0x6e, 0x84, 0xae, 0x81, 0x82,
	0x5d, 0xe4, 0xa8, 0xa8, 0xb8, 0x89, 0x32, 0x6b, 0x0d, 0x30, 0x06, 0x47, 0x4b, 0xa9, 0x90, 0x9f,
	0x58, 0xc2, 0xae, 0x0b, 0xc7, 0xf7, 0xf8, 0x85, 0x5e, 0x6b, 0x2d, 0x73, 0x91, 0xf0, 0x8e, 0x73,
	0x6c, 0x40, 0xcd, 0x2b, 0xec, 0xee, 0x5f, 0x21, 0x87, 0xce, 0x4a, 0x0b, 0xa9, 0xde, 0xce, 0x79,
	0xcf, 0x31, 0x65, 0xc9, 0x1e, 0xc3, 0xd9, 0x47, 0x21, 0x49, 0xaa, 0x38, 0xc2, 0x75, 0xaa, 0x36,
	0x86, 0x83, 0x15, 0xdc, 0x40, 0x0b, 0xf7, 0x12, 0xb1, 0x89, 0xfb, 0xce, 0xbd, 0x01, 0xb1, 0x01,
	0xb4, 0x57, 0xab, 0x25, 0x3f, 0x1d, 0x7b, 0x93, 0x76, 0x58, 0x2c, 0xfd, 0x1f, 0x1e, 0xdc, 0xdd,
	0x7b, 0x59, 0x66, 0x97, 0x2a, 0x83, 0xec, 0x29, 0xf4, 0x2a, 0xcc, 0x70, 0x6f, 0xdc, 0x9e, 0xf4,
	0x67, 0x6c, 0x7a, 0xfd, 0xbc, 0xaf, 0xe5, 0xb5, 0xe8, 0xd6, 0x01, 0xb7, 0x6e, 0x1f, 0x30, 0xf3,
	0xe1, 0x34, 0x44, 0x93, 0x25, 0xb4, 0x44, 0x15, 0xd3, 0xa5, 0x1d, 0xcd, 0x71, 0xb8, 0x87, 0xcd,
	0xbe, 0xc2, 0x9d, 0x6a, 0xf3, 0x08, 0x75, 0x2e, 0xd7, 0xc8, 0x62, 0xe8, 0x37, 0xb2, 0xb2, 0x51,
	0x1d, 0xe8, 0xf0, 0x73, 0x0c, 0x1f, 0xfc, 0x83, 0x75, 0x07, 0xf4, 0xef, 0x7f, 0xfb, 0xf9, 0xeb,
	0x7b, 0xeb, 0x9e, 0x3f, 0x08, 0xf2, 0x67, 0x41, 0x8c, 0xf4, 0xa4, 0x52, 0xbf, 0xf2, 0xce, 0x2f,
	0x4e, 0xec, 0x2f, 0x78, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x10, 0xcb, 0xfe, 0xd1, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScheduleServiceClient is the client API for ScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScheduleServiceClient interface {
	GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error)
}

type scheduleServiceClient struct {
	cc *grpc.ClientConn
}

func NewScheduleServiceClient(cc *grpc.ClientConn) ScheduleServiceClient {
	return &scheduleServiceClient{cc}
}

func (c *scheduleServiceClient) GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error) {
	out := new(GetScheduleResponse)
	err := c.cc.Invoke(ctx, "/schedule.ScheduleService/GetSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServiceServer is the server API for ScheduleService service.
type ScheduleServiceServer interface {
	GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error)
}

// UnimplementedScheduleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedScheduleServiceServer struct {
}

func (*UnimplementedScheduleServiceServer) GetSchedule(ctx context.Context, req *GetScheduleRequest) (*GetScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchedule not implemented")
}

func RegisterScheduleServiceServer(s *grpc.Server, srv ScheduleServiceServer) {
	s.RegisterService(&_ScheduleService_serviceDesc, srv)
}

func _ScheduleService_GetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule.ScheduleService/GetSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetSchedule(ctx, req.(*GetScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ScheduleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schedule.ScheduleService",
	HandlerType: (*ScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchedule",
			Handler:    _ScheduleService_GetSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schedule.proto",
}
